package integrales;

import javax.swing.JOptionPane;
import de.congrace.exp4j.Calculable;
import de.congrace.exp4j.ExpressionBuilder;
import de.congrace.exp4j.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.math.plot.Plot2DPanel;
import org.math.plot.plotObjects.BaseLabel;

/**
 *
 * @author Alejandra
 */
public class PantallaIntegrales extends javax.swing.JFrame {

    /**
     * Creates new form PantallaIntegracion
     */
    double [] xRiermman;
    double [] yRiermman;
    double [] xRiermman1;
    double [] yRiermman1;
    public PantallaIntegrales() {
        
        initComponents();
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setLocationRelativeTo(null);
        setVisible(true);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INTEGRACIÓN NUMÉRICA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("INGRESO DE DATOS"));

        jLabel4.setText("TAMAÑO PARTICIÓN");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(" ∫ ");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("dx");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(29, 29, 29))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("SALIDA"));

        jButton3.setText("RIEMANN IZQ.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("RIEMANN DER.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("TRAPECIOS.");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("SIMPSON 1/3");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(14, 14, 14)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         double a, b, n;
        try 
        {
            double sumatoria = 0;
            String funcion = jTextField1.getText();
            a = Integer.parseInt(jTextField2.getText());
            b = Integer.parseInt(jTextField3.getText());
            n = Integer.parseInt(jTextField4.getText());
            double h = calcularH(a, b, n);
            double resultadoRiemannIzq = sumatoriaRiemannIzq(funcion, h, n, a);
            jTextField8.setText(String.valueOf(resultadoRiemannIzq));
            //graficarRiemmanIzquierda();
        } catch (NumberFormatException nfe) 
        {
            JOptionPane.showMessageDialog(null, "Error en el ingreso de datos", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
        } catch (UnknownFunctionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnparsableExpressionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           double a, b, n;
        try 
        {
            double sumatoria = 0;
            String funcion = jTextField1.getText();
            a = Integer.parseInt(jTextField2.getText());
            b = Integer.parseInt(jTextField3.getText());
            n = Integer.parseInt(jTextField4.getText());
            double h = calcularH(a, b, n);
            double resultadoRiemannDer = sumatoriaRiemannDer(funcion, h, n, a);
            jTextField9.setText(String.valueOf(resultadoRiemannDer));
            //graficarRiemmanDerecha();
        } catch (NumberFormatException nfe) 
        {
            JOptionPane.showMessageDialog(null, "Error en el ingreso de datos", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
        } catch (UnknownFunctionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnparsableExpressionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         double a, b, n;
        try 
        {
            double sumatoria = 0;
            String funcion = jTextField1.getText();
            a = Integer.parseInt(jTextField2.getText());
            b = Integer.parseInt(jTextField3.getText());
            n = Integer.parseInt(jTextField4.getText());
            double h = calcularH(a, b, n);
            double resultadoTrapecio = sumatoriaTrapecios(funcion, h, n, a, b);
            jTextField10.setText(String.valueOf(resultadoTrapecio));
            //graficarTrapecios();
        } catch (NumberFormatException nfe) 
        {
            JOptionPane.showMessageDialog(null, "Error en el ingreso de datos", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
        } catch (UnknownFunctionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnparsableExpressionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                 double a, b, n;
        try 
        {
            double sumatoria = 0;
            String funcion = jTextField1.getText();
            a = Integer.parseInt(jTextField2.getText());
            b = Integer.parseInt(jTextField3.getText());
            n = Integer.parseInt(jTextField4.getText());
            double h = calcularH(a, b, n);
            double resultadoSimpson = sumatoriaSimpson(funcion, h, n, a);
            jTextField11.setText(String.valueOf(resultadoSimpson));
        } catch (NumberFormatException nfe) 
        {
            JOptionPane.showMessageDialog(null, "Error en el ingreso de datos", "¡Alerta!", JOptionPane.INFORMATION_MESSAGE);
        } catch (UnknownFunctionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnparsableExpressionException ex) {
            Logger.getLogger(PantallaIntegrales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
//public void graficarRiemmanIzquierda()
//{
//    Plot2DPanel plot = new Plot2DPanel();
//         plot.addLegend("SOUTH");
//        plot.addLinePlot("Funcion", xRiermman1,yRiermman1);
//        BaseLabel titulo = new BaseLabel("SUMATORIA RIEMANN", Color.blue, 0.5,1.1);
//        plot.addPlotable(titulo);
//        double a1[] = {xRiermman[0],0.0};
//        double a2[] = {xRiermman[0],yRiermman[0]};
//        plot.addLinePlot("",Color.RED,a1,a2);
//        for (int i = 1; i < xRiermman.length; i++) {
//            double v1[] = {xRiermman[i],0.0};
//            double v2[] = {xRiermman[i],yRiermman[i]};
//            plot.addLinePlot("",Color.RED,v1,v2);
//        }
//        for (int i = 0; i < xRiermman.length-1; i++) {
//            double h1[] = {xRiermman[i],yRiermman[i]};
//            double h2[] = {xRiermman[i+1],yRiermman[i]};
//            plot.addLinePlot("",Color.RED,h1,h2);
//        }
//        JFrame frame = new JFrame("INTEGRACION NUMERICA");
//        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        frame.setSize(600,500);
//        frame.add(plot,BorderLayout.CENTER);
//        frame.setVisible(true);
//}
//
//public void graficarRiemmanDerecha()
//{
//    Plot2DPanel plot = new Plot2DPanel();
//         plot.addLegend("SOUTH");
//        plot.addLinePlot("Funcion", xRiermman,yRiermman);
//        BaseLabel titulo = new BaseLabel("SUMATORIA RIEMANN", Color.blue, 0.5,1.1);
//        plot.addPlotable(titulo);
//        double a1[] = {xRiermman[xRiermman.length-1],0.0};
//        double a2[] = {xRiermman[xRiermman.length-1],yRiermman[xRiermman.length-1]};
//        plot.addLinePlot("",Color.RED,a1,a2);
//        for (int i = xRiermman.length-2; i >= 0; i--) {
//            double v1[] = {xRiermman[i],0.0};
//            double v2[] = {xRiermman[i],yRiermman[i+1]};
//            plot.addLinePlot("",Color.RED,v1,v2);
//        }
//        for (int i = 0; i < xRiermman.length-1; i++) {
//            double h1[] = {xRiermman[i],yRiermman[i+1]};
//            double h2[] = {xRiermman[i+1],yRiermman[i+1]};
//            plot.addLinePlot("",Color.RED,h1,h2);
//        }
//        JFrame frame = new JFrame("INTEGRACION NUMERICA");
//        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        frame.setSize(600,500);
//        frame.add(plot,BorderLayout.CENTER);
//        frame.setVisible(true);
//}
//public void graficarTrapecios()
//{
//    Plot2DPanel plot = new Plot2DPanel();
//         plot.addLegend("SOUTH");
//        plot.addLinePlot("Funcion", xRiermman1,yRiermman1);
//        BaseLabel titulo = new BaseLabel("SUMATORIA TRAPECIOS", Color.blue, 0.5,1.1);
//        plot.addPlotable(titulo);
//        double a1[] = {xRiermman[0],0.0};
//        double a2[] = {xRiermman[0],yRiermman[0]};
//        plot.addLinePlot("",Color.RED,a1,a2);
//        for (int i = 1; i < xRiermman.length; i++) {
//            double v1[] = {xRiermman[i],0.0};
//            double v2[] = {xRiermman[i],yRiermman[i]};
//            plot.addLinePlot("",Color.RED,v1,v2);
//        }
//        for (int i = 0; i < xRiermman.length-1; i++) {
//            double h1[] = {xRiermman[i],yRiermman[i]};
//            double h2[] = {xRiermman[i+1],yRiermman[i+1]};
//            plot.addLinePlot("",Color.RED,h1,h2);
//        }
//        JFrame frame = new JFrame("INTEGRACION NUMERICA");
//        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        frame.setSize(600,500);
//        frame.add(plot,BorderLayout.CENTER);
//        frame.setVisible(true);
//}
    
    public double funcc(String funcion, double x) throws UnknownFunctionException, UnparsableExpressionException
    {
        Calculable calc = new ExpressionBuilder(funcion)
                    .withVariable("x", x)
//                    .withVariable("y", y)
                    .build();
                    double result1 = calc.calculate();
                    return result1;
    }
    
    //Usar esta en caso de error del constructor para funciones de las derivadas
//    public double funcionDerivada(double x)
//    {
//        double a = x-1, b=x+1;
//        double funcion = Math.sqrt(a/b);
//        return funcion;
//    }
    public double calcularH(double a, double b, double n) {
        double h = 0.00d;
        h = (b - a) / n;
        return h;
    }

    public double sumatoriaRiemannDer(String funcion, double h, double n, double a) throws UnknownFunctionException, UnparsableExpressionException {
        double sumatoria = 0.000d;
        for (int i = 1; i <= n; i++) {
            double x = (a + (i * h));
            double r = funcc(funcion, x);
            sumatoria = sumatoria + (h * (r));
        }
        int p =(int)(n);
        xRiermman=new double[p];
        yRiermman=new double[p];
        for (int i = 1; i <= p; i++) {
            double x = (a + (i * h));
            double r = funcc(funcion, x);
            xRiermman[i-1]= x;
            yRiermman[i-1]= r;
        }
        return sumatoria;
    }

    public double devuelveFuncion(double x) {
        double funcion = x * x;
        return funcion;
    }

    public double sumatoriaRiemannIzq(String funcion, double h, double n, double a) throws UnknownFunctionException, UnparsableExpressionException {
        double sumatoria = 0.000d;
        for (int i = 0; i < n; i++) {
            double x = (a + (i * h));
            //sumatoria = sumatoria + (h * (devuelveFuncion(x)));
            sumatoria = sumatoria + (h * (funcc(funcion, x)));
        }
        int p =(int)(n);
        int q =(int)(n*10);
        double h1=h/10;
        xRiermman=new double[p];
        yRiermman=new double[p];
        xRiermman1=new double[q];
        yRiermman1=new double[q];
        for (int i = 1; i <= p; i++) {
            double x = (a + (i * h));
            double r = funcc(funcion, x);
            xRiermman[i-1]= x;
            yRiermman[i-1]= r;
        }
        for (int i = 1; i <= q; i++) {
            double x = (a + (i * h1));
            double r = funcc(funcion, x);
            xRiermman1[i-1]= x;
            yRiermman1[i-1]= r;
        }
        return sumatoria;
    }

 
    public double sumatoriaTrapecios(String funcion, double h, double n, double a, double b) throws UnknownFunctionException, UnparsableExpressionException
    {
     
        double suma=(funcc(funcion, a)+funcc(funcion, b))/2;
        for(int i=1; i<n; i++){
            suma+=funcc(funcion,(a+i*h));
        }
        return suma*h;
    
    }

    public double sumatoriaSimpson(String funcion, double h, double n, double a) throws UnknownFunctionException, UnparsableExpressionException {
        double pares = 0.000d, impares = 0.000d, sumatoria = 0.000d;
        for (int i = 1; i < n; i = i + 2) {
            double x = (a + (i * h));
            //impares = impares + devuelveFuncion(x);
            impares = impares + funcc(funcion, x);
        }

        for (int i = 2; i <= n; i = i + 2) {
            double x = (a + (i * h));
            //pares = pares + devuelveFuncion(x);
            pares = pares + funcc(funcion, x);
        }
        //sumatoria = (h / 3) * (devuelveFuncion(a) + (2 * pares) + (4 * impares)); //este es el que vale
        sumatoria = (h / 3) * (funcc(funcion, a) + (2 * pares) + (4 * impares));
        //sumatoria = (h/3) * (devuelveFuncion(a) + (4*pares) + (2*impares));
        return sumatoria;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaIntegrales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaIntegrales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaIntegrales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaIntegrales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaIntegrales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
